name: CI/CD Autenticacion y autorizacion A
on: [push]
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_AUTH_A }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_AUTH_A }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_AUTH_A }}

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/autenticacion-autorizacion-A' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/autenticacion-autorizacion-A' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install Verce CLI
        run: yarn global add vercel@latest
      - name: Pull Vercel Enviromental Variables
        run: vercel pull --yes --token=${{secrets.VERCEL_TOKEN_AUTH_A }}
      - name: Trigger Vercel deployment
        run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN_AUTH_A }}